In [6]:
import numpy as np

# numpy array

In [36]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
arr2= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
              ])

print(arr2)
print("SIZE: ", arr2.size)
print("SHAPE:", arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
SIZE:  9
SHAPE: (3, 3)


In [33]:
arr3 = np.zeros((3,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
arr4 = arr1*3
print(arr4)

[ 3  6  9 12 15]


In [4]:
arr5 = arr2*5
print(arr5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [10]:
arr3d = np.array([[
    [1, 2, 3],
    [2, 1, 3],
    [3, 1, 2]
    ]])

print(arr3d)

[[[1 2 3]
  [2 1 3]
  [3 1 2]]]


# NUMPY DAY2
